/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CartItemInterface } from "./components/cart/cart.interfaces";
export namespace Components {
    interface WowxCart {
        "cartItems": Array<CartItemInterface>;
    }
    interface WowxCartFooter {
        "savings": string;
    }
    interface WowxCartHeader {
        "link": string;
        "manufacturerName": string;
        "productName": string;
    }
    interface WowxCartImage {
        "alt": string;
        "src": string;
    }
    interface WowxCartSubtotal {
        "maxQty": number;
        "price": number;
        "productId": string;
    }
}
declare global {
    interface HTMLWowxCartElement extends Components.WowxCart, HTMLStencilElement {
    }
    var HTMLWowxCartElement: {
        prototype: HTMLWowxCartElement;
        new (): HTMLWowxCartElement;
    };
    interface HTMLWowxCartFooterElement extends Components.WowxCartFooter, HTMLStencilElement {
    }
    var HTMLWowxCartFooterElement: {
        prototype: HTMLWowxCartFooterElement;
        new (): HTMLWowxCartFooterElement;
    };
    interface HTMLWowxCartHeaderElement extends Components.WowxCartHeader, HTMLStencilElement {
    }
    var HTMLWowxCartHeaderElement: {
        prototype: HTMLWowxCartHeaderElement;
        new (): HTMLWowxCartHeaderElement;
    };
    interface HTMLWowxCartImageElement extends Components.WowxCartImage, HTMLStencilElement {
    }
    var HTMLWowxCartImageElement: {
        prototype: HTMLWowxCartImageElement;
        new (): HTMLWowxCartImageElement;
    };
    interface HTMLWowxCartSubtotalElement extends Components.WowxCartSubtotal, HTMLStencilElement {
    }
    var HTMLWowxCartSubtotalElement: {
        prototype: HTMLWowxCartSubtotalElement;
        new (): HTMLWowxCartSubtotalElement;
    };
    interface HTMLElementTagNameMap {
        "wowx-cart": HTMLWowxCartElement;
        "wowx-cart-footer": HTMLWowxCartFooterElement;
        "wowx-cart-header": HTMLWowxCartHeaderElement;
        "wowx-cart-image": HTMLWowxCartImageElement;
        "wowx-cart-subtotal": HTMLWowxCartSubtotalElement;
    }
}
declare namespace LocalJSX {
    interface WowxCart {
        "cartItems"?: Array<CartItemInterface>;
    }
    interface WowxCartFooter {
        "savings"?: string;
    }
    interface WowxCartHeader {
        "link"?: string;
        "manufacturerName"?: string;
        "productName"?: string;
    }
    interface WowxCartImage {
        "alt"?: string;
        "src"?: string;
    }
    interface WowxCartSubtotal {
        "maxQty"?: number;
        "onSubtotalUpdated"?: (event: CustomEvent<any>) => void;
        "price"?: number;
        "productId"?: string;
    }
    interface IntrinsicElements {
        "wowx-cart": WowxCart;
        "wowx-cart-footer": WowxCartFooter;
        "wowx-cart-header": WowxCartHeader;
        "wowx-cart-image": WowxCartImage;
        "wowx-cart-subtotal": WowxCartSubtotal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wowx-cart": LocalJSX.WowxCart & JSXBase.HTMLAttributes<HTMLWowxCartElement>;
            "wowx-cart-footer": LocalJSX.WowxCartFooter & JSXBase.HTMLAttributes<HTMLWowxCartFooterElement>;
            "wowx-cart-header": LocalJSX.WowxCartHeader & JSXBase.HTMLAttributes<HTMLWowxCartHeaderElement>;
            "wowx-cart-image": LocalJSX.WowxCartImage & JSXBase.HTMLAttributes<HTMLWowxCartImageElement>;
            "wowx-cart-subtotal": LocalJSX.WowxCartSubtotal & JSXBase.HTMLAttributes<HTMLWowxCartSubtotalElement>;
        }
    }
}
